export type SubScreen =
  | "about"
  | "profile"
  | "notifications"
  | "alerts"
  | "emergency-hub"
  | "flatmates"
  | "house-rules"
  | "chores"
  | "bills"
  | "calendar"
  | "emergency"
  | "maintenance"
  | "flat-feed"
  | "ai-assistant"
  | "documents"
  | "bond-tracker"
  | "checklists"
  | "expenses"
  | "availability"
  | "shopping-list"
  | "visitors"
  | "utility-analytics"
  | "lease-timeline"
  | "house-vibe"
  | "maintenance-history"
  | "gallery"
  | "agreement"
  | "announcements"
  | "property-health"
  | "property-search"
  | "property-detail"
  | "landlord-notifications";

export type OverlayScreen = "chat" | null;
